### ISSUE TITLE
Emissive texture does not create a visible difference

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#129]
Two models, one with emissive set and the other without, look identical. 

- If I use Occlusion instead of Emissive, I can see the occlusion texture.
- Using the same UV cords for both basecolortexture and emissive does not make emissive viewable

Model 4 is just a basecolortexture
Model 5 is the same basecolortexture, but with an emissive texture set for the left side of the model

[Samples.zip](https://github.com/bghgary/glTF-Asset-Generator/files/1319158/Samples.zip)

**Comment by kcoley** [comment]
Taking a look...

**Comment by kcoley** [comment]
Turns out the emissive factor would also have to be defined.  If not, it defaults to [0,0,0], which effectively makes the texture not render:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#material

To verify, I added an "emissiveFactor" parameter to the glTF file and set the values to 1 for the materials.
