### ISSUE TITLE
Add 'expected render' screenshot of each model in readme table

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#301]
- [x] Generate screenshots/gifs
- [x] Insert images into readme tables

**Comment by bwasty** [comment]
Do you have a tool yet to generate the screenshots? 
I quickly wrote a script for my [gltf-viewer](https://github.com/bwasty/gltf-viewer): https://github.com/bghgary/glTF-Asset-Generator/commit/5f6be5c4b5a29dd5dec15f424574bddf8001c527
Here are the results: https://github.com/bwasty/glTF-Asset-Generator/tree/gltf-viewer (see subpages with reference images).
A few images are missing/wrong because some features are not implemented yet (primitive modes, TEX_COORD_1, alpha mode + cutoff ... https://github.com/bwasty/gltf-viewer/issues/3)

(And I had to do some small adjustments to camera and light: https://github.com/bwasty/gltf-viewer/commit/56604b018f18e3b5b80b6265ff3b2d6cb6ecc988)

**Comment by bghgary** [comment]
Yes, @kcoley is working on a screenshot generator.

I'm assuming you are asking because you want to compare the results from your implementation against the reference. I discussed this a bit with the Khronos working group. I think it makes more sense for each implementation to do this work. We can possibly create a new repo that include some test harness code to help with web implementations.

**Comment by donmccurdy** [comment]
^One extra thought from my suggestion of adding URL of reference screenshot in the manifest, perhaps we also include the camera transform? Would make it much easier for other implementations to match.

**Comment by bghgary** [comment]
> perhaps we also include the camera transform?

Hmm, interesting. Let's review this once we have the reference images.

**Comment by bghgary** [comment]
This is complete.
