### ISSUE TITLE
Node_NegativeScale - textures get progressively bigger in the README.md file

### ISSUE THREAD

**Issue by kcoley** [bghgary/glTF-Asset-Generator#358]
- [ ] Node_NegativeScale - Normal texture, Base Color texture and Metal Roughness textures should be the same size in the table 

<img width="228" alt="screenshots" src="https://user-images.githubusercontent.com/3946928/37001105-4e1ebe96-207a-11e8-8a1d-e56b981237a4.PNG">

**Comment by stevk** [comment]
This is a consequence of allowing the images to scale. The 'Metallic Roughness Texture' thumbnail has more space than the other texture due to having a wider name. I don't think we should fix this, but here are the options.

1. Use smaller thumbnails
2. Add nbsp to the attribute name at the top of the column to force those columns to be wider.

**Comment by kcoley** [comment]
"Fixed"
